package faest

import (
	"bytes"
	"encoding/json"
	"os"
	"testing"

	"github.com/maceip/tamayo/field"
)

// Reference vectors generated by tools/qs2_dump.cpp running against the
// stipulated source (pq_blind_signatures vole/optimized_bs/quicksilver.hpp,
// max_deg=2) on the x86-64 reference box. Every case carries all inputs
// (witness incl. mask bytes, VOLE tags and keys, delta, challenge) and the
// reference outputs (proof, prover check, verifier check).
type qs2Vec struct {
	Secpar        int    `json:"secpar"`
	Kind          string `json:"kind"`
	N             int    `json:"n"`
	WitnessBits   int    `json:"witness_bits"`
	Witness       string `json:"witness"`
	Tags          string `json:"tags"`
	Keys          string `json:"keys"`
	Delta         string `json:"delta"`
	Challenge     string `json:"challenge"`
	Proof         string `json:"proof"`
	CheckProver   string `json:"check_prover"`
	CheckVerifier string `json:"check_verifier"`
}

func splitElems(f field.Big, b []byte) [][]uint64 {
	out := make([][]uint64, len(b)/f.Bytes)
	for i := range out {
		out[i] = f.FromBytes(b[i*f.Bytes : (i+1)*f.Bytes])
	}
	return out
}

func qs2Field(t *testing.T, secpar int) field.Big {
	switch secpar {
	case 128:
		return field.Big128
	case 192:
		return field.Big192
	case 256:
		return field.Big256
	}
	t.Fatalf("unknown secpar %d", secpar)
	return field.Big{}
}

// runQS2Circuit replays the constraint circuit of one vector kind on both
// sides, mirroring the corresponding loop of tools/qs2_dump.cpp.
func runQS2Circuit(t *testing.T, v qs2Vec, p *QS2Prover, vf *QS2Verifier, f field.Big) {
	n := v.N
	for i := 0; i < n; i++ {
		switch v.Kind {
		case "gf256_mul":
			xp := p.LoadWitness8BitsAndCombine(8 * i)
			yp := p.LoadWitness8BitsAndCombine(8 * (n + i))
			wp := p.LoadWitness8BitsAndCombine(8 * (2*n + i))
			p.AddConstraint(xp.Mul(yp).Add(wp))
			xv := vf.LoadWitness8BitsAndCombine(8 * i)
			yv := vf.LoadWitness8BitsAndCombine(8 * (n + i))
			wv := vf.LoadWitness8BitsAndCombine(8 * (2*n + i))
			vf.AddConstraint(xv.Mul(yv).Add(wv))
		case "gf16_mul":
			xp := p.LoadWitness4BitsAndCombine(4 * i)
			yp := p.LoadWitness4BitsAndCombine(4 * (n + i))
			wp := p.LoadWitness4BitsAndCombine(4 * (2*n + i))
			p.AddConstraint(xp.Mul(yp).Add(wp))
			xv := vf.LoadWitness4BitsAndCombine(4 * i)
			yv := vf.LoadWitness4BitsAndCombine(4 * (n + i))
			wv := vf.LoadWitness4BitsAndCombine(4 * (2*n + i))
			vf.AddConstraint(xv.Mul(yv).Add(wv))
		case "xor_deg1":
			xp := p.LoadWitness8BitsAndCombine(8 * i)
			yp := p.LoadWitness8BitsAndCombine(8 * (n + i))
			wp := p.LoadWitness8BitsAndCombine(8 * (2*n + i))
			p.AddConstraint(xp.Add(yp).Add(wp))
			xv := vf.LoadWitness8BitsAndCombine(8 * i)
			yv := vf.LoadWitness8BitsAndCombine(8 * (n + i))
			wv := vf.LoadWitness8BitsAndCombine(8 * (2*n + i))
			vf.AddConstraint(xv.Add(yv).Add(wv))
		case "inv_one":
			xp := p.LoadWitness8BitsAndCombine(8 * i)
			ip := p.LoadWitness8BitsAndCombine(8 * (n + i))
			p.AddConstraint(xp.Mul(ip).AddOne())
			xv := vf.LoadWitness8BitsAndCombine(8 * i)
			iv := vf.LoadWitness8BitsAndCombine(8 * (n + i))
			vf.AddConstraint(xv.Mul(iv).AddOne())
		case "scalar_mul":
			c := f.ByteCombineBits(byte(0xc3 + i))
			xp := p.LoadWitness8BitsAndCombine(8 * i)
			wp := p.LoadWitness8BitsAndCombine(8 * (n + i))
			p.AddConstraint(xp.MulScalar(c).Add(wp))
			xv := vf.LoadWitness8BitsAndCombine(8 * i)
			wv := vf.LoadWitness8BitsAndCombine(8 * (n + i))
			vf.AddConstraint(xv.MulScalar(c).Add(wv))
		default:
			t.Fatalf("unknown kind %q", v.Kind)
		}
	}
}

// TestQuickSilver2KAT verifies the degree-2 QuickSilver against reference
// vectors from the optimized_bs C++ implementation: the prover must reproduce
// the reference proof and check bytes exactly, and the verifier, given the
// reference proof, must reproduce the reference check bytes exactly.
func TestQuickSilver2KAT(t *testing.T) {
	raw, err := os.ReadFile("testdata/quicksilver2.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var vecs []qs2Vec
	if err := json.Unmarshal(raw, &vecs); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(vecs) == 0 {
		t.Fatal("no vectors")
	}

	for _, v := range vecs {
		f := qs2Field(t, v.Secpar)
		witness := mustHex(t, v.Witness)
		tags := splitElems(f, mustHex(t, v.Tags))
		keys := splitElems(f, mustHex(t, v.Keys))
		delta := f.FromBytes(mustHex(t, v.Delta))
		challenge := mustHex(t, v.Challenge)
		refProof := mustHex(t, v.Proof)
		refCheckP := mustHex(t, v.CheckProver)
		refCheckV := mustHex(t, v.CheckVerifier)

		prover := NewQS2Prover(f, witness, tags, challenge)
		verifier := NewQS2Verifier(f, keys, delta, challenge)
		runQS2Circuit(t, v, prover, verifier, f)

		proof, checkP := prover.Prove(v.WitnessBits)
		if !bytes.Equal(proof, refProof) {
			t.Errorf("%d/%s: prover proof mismatch\n got %x\nwant %x", v.Secpar, v.Kind, proof, refProof)
			continue
		}
		if !bytes.Equal(checkP, refCheckP) {
			t.Errorf("%d/%s: prover check mismatch\n got %x\nwant %x", v.Secpar, v.Kind, checkP, refCheckP)
			continue
		}

		// Verifier consumes the reference proof bytes (interop direction).
		checkV := verifier.Verify(v.WitnessBits, refProof)
		if !bytes.Equal(checkV, refCheckV) {
			t.Errorf("%d/%s: verifier check mismatch\n got %x\nwant %x", v.Secpar, v.Kind, checkV, refCheckV)
			continue
		}
		if !bytes.Equal(checkP, checkV) {
			t.Errorf("%d/%s: prover/verifier check disagree", v.Secpar, v.Kind)
		}
	}
	t.Logf("verified %d deg-2 QuickSilver reference vectors byte-exact", len(vecs))
}
